### ISSUE TITLE
Make it a monorepo

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/paneron#49] opened 2022-09-22 10:40 UTC
... with pnpm, and migrate extensions into this repo.

This is from a conversation with @strogonoff .  Idea is that Paneron and the extensions have tight version dependencies, so having them in a monorepo would make testing, etc. more maintainable.

**Comment by ronaldtse** [comment] 2022-09-22 11:45
There is a high risk that this prevents independent releases of extensions and obscures the need of a defined interface between the core and extensions (i.e. developers will be lazy to define the interface because it is so easy to change all extensions at once).

I do not know if this is a good idea.

**Comment by strogonoff** [comment] 2022-09-23 17:38
For the record, I pushed https://github.com/paneron/monorepo some time ago, I have unpushed changes but it’s not complete so might not be worth to push it.

> There is a high risk that this prevents independent releases of extensions and obscures the need of a defined interface between the core and extensions (i.e. developers will be lazy to define the interface because it is so easy to change all extensions at once).

I made arguments for this before so I don’t want to repeat myself too much, besides the pattern is well-documented elsewhere. I think the arguments against it so far stem from not fully understanding how it works.

It is a reality that our package versions depend on each other, this is not something that can be avoided. API changes happen all the time, and this can’t be avoided either. 

Currently if I am making a change to Paneron API I need to make tons of commits to every extension using this API, make sure everything works together and make all relevant releases simultaneously. This is an error-prone process and a situation where published packages are out of sync is easy to enter inadvertently. It also complicates and significantly slows down any sort of integration tests, and in fact moving to a monorepo was intended as a step towards a reliable test system for Paneron core ecosystem.

Actually, the situation is not dissimilar to Relaton, where we have very similar issues. With Relaton we can’t easily put all core packages (relaton-py, relaton-cli, gems) in a monorepo because they use different stacks and package management systems (Python, Ruby, etc.) and monorepo pattern is not developed in such a scenario (although if I were in charge of Relaton, and I knew that monorepo tooling is as strong in Ruby world as it is in TypeScript world, I would definitely move at least all Ruby gems into a single repository ASAP). However, since Paneron so far sticks to JS/TS, it’s very realistic.

If we want to get to a reliable production-grade product, we must be able to iterate fast. In fact, Relaton’s schema is already actually supposed to be more stable than Paneron’s extension API, and you can see how often it changes and how quickly schema spec simply goes out of date and parts of core ecosystem are not always compatible with each other. Paneron, meanwhile, uses TypeScript—which is a big advantage, as not complying with the schema will literally not compile—and Paneron’s extension API is due for a much bigger revamp and must undergo many changes in short time compared to Relaton. If we can keep everything working together in meantime, it’s worth pursuing.

This pattern is not something I came up with, you can find it used for [React](https://github.com/facebook/react/tree/main/packages) (where and many other popular projects. Git specification & reference implementation is moving in the direction of facilitating monorepos with features like partial checkout and others. I don’t think it’s far-fetched to say it’s consensus to use monorepos in our circumstances.

**Comment by ronaldtse** [comment] 2022-09-27 05:59
I understand how monorepos work and therefore also aware of the pitfalls. As long as we can document the defined interfaces (the extension mechanism) and allow 3rd-parties to create/manage extensions outside our repo, I'm fine with a monorepo.

There are also other approaches that people use to simplify dependency issues, such as Google's latest practice of "always use Git HEAD", which seems to me as an anti-pattern.

In any case, please proceed with this. Thanks.

**Comment by strogonoff** [comment] 2022-09-27 14:21
OK. Always using HEAD doesn’t strike me as something that would work for Paneron, unless we literally disable the app for all users whenever the new version comes out until they update.

**Closed** 2022-12-04 04:16 UTC
Labels: enhancement
